### ISSUE TITLE
Workflow Issues Management is Expensive

### ISSUE THREAD

**Issue by lucyskyy** [revas/ecosystem#16]
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

## Benefits

We can spare time writing issues and we can clearly see every step of any issue, as if now we can't understand which version is the issues referring to. With the indication of the version we can organize the work better.

## Possible Solution (optional)

1. Remove the body of the issue
2. In the title of the issue write the version 
3. Add the label 'workflow' and one with the number of the version

## Context
1. Workflow issue are all the same
2. We don't know to which version the issue is referring to
3. Workflow issues are not differentiated from the enhanchement and bug labels.

**Comment by davidegiovanni** [comment]
Nice way to better handle the issues for the wireframe 🥇

**Comment by samanthabaita** [comment]
Yes, I agree. We can avoid to write the same description over and over by writing it once.

**Comment by hashbardd** [comment]
@lucyskyy Can you create a new github template for workflows issues? Maybe you can use quotes to describe the correct usage of the tags. 😄

**Comment by lucyskyy** [comment]
All right!

**Comment by lucyskyy** [comment]
Which branch do I use?

**Comment by hashbardd** [comment]
Well, you already forked the repository. You can create a `docs/16-workflow-template` branch if you like the name 😄
