### ISSUE TITLE
Enhancing Wireframe Documentation

### ISSUE THREAD

**Issue by samanthabaita** [revas/ecosystem#20]
I think the way we define wireframes could be improved with a more organized structure that can help the handoff between design and development.

This could be achieved with these document settings:
- the SVG of the wireframe of the screen with title
- the triggers for each triggerable component
- the consequent reaction 

This can be applied to every screen that has been designed.

**Comment by samanthabaita** [comment]
What do you think about making the triggerable elements more visible by giving them a different color on the wireframe? 🤔

**Comment by davidegiovanni** [comment]
I agree and I also think that we could create a similiar structure:

* ✍️ name of the screen
* 🖼 SVG of the screen with higlighted triggerable elements;
* 🔥 [trigger] on [component name] = [behavior] for behavior of components @ special events;
* 🔥 [trigger] on [component name] = [transition to[screen name]] for behaviors of components @ special events that have transitions as outputs ;
* 🎥 specs for [animation/transition] if needed.

What do you think?

**Comment by davidegiovanni** [comment]
The 🎥 **specs for the transitions** can be structured as follow:

* [initial screen] to [final screen];
* [manipulated components and patterns];
* [manipulated variables], such as *opacity*, or *size* or *color*;
* [initial value of the variable] and [final value of the variable];
* definition of the easing curve with parametres;

**Comment by samanthabaita** [comment]
@davidegiovanni Yes I think that the structure you just described, can be understood and clear for whoever reads.

**Comment by samanthabaita** [comment]
I saw that during tests the devs have available only a short amount of triggers, so I think we should talk with @lykkechen & @hashbardd to have a common :fire: trigger list.

**Comment by davidegiovanni** [comment]
Yeah, it woul be better to hear also from who will implement those wireframes

**Comment by hashbardd** [comment]
You can use e2e cypress api to understand the abstraction of the user interaction. Eg. `click`, `focus`, `hover`. You can also describe the required state of the system after an action with the `should` command.

https://docs.cypress.io/api/introduction/api.html# (Section Commands)

**Comment by samanthabaita** [comment]
Thanks for the link. :smile: 

I've read all the documentation and I think we should consider using the following commands:
- `blur`
- `click`
- `focus`
- `focused`
- `hover`
- `invoke`
- `not`
- `should`
- `type`
- `viewport`
- `wait`

These are the ones I think that could be useful as :fire: triggers in the wireframes and then in tests. 
Maybe these are too many or they are not enough, but we can't aswer these question before a little trial. @davidegiovanni 

@lykkechen What do you think about this list? In the past tests did you use these :fire: triggers?

**Comment by samanthabaita** [comment]
@davidegiovanni I think we should consider making a list of base components and a little _how to name SVG files_ guide.

**Comment by samanthabaita** [comment]
@revas/designers  I think that we could also organize the design folder in subfolders, one for each component described in the specs. In there we could have all the screens. 

About naming, I thought we could use a structure similar to this one:
``` [state]-[type of component]-[desktop/mobile].svg ```

@revas/everyone what do you think?

**Comment by lykkechen** [comment]
I liked the proposed structures for the specs and also the transitions. Also great the idea of giving different color to triggerable elements.
I think it would be practical also to have the desktop wireframes side by side with the mobile ones.
@samanthabaita About the list of triggers, I only used a few like `click`, `should` because I'm not that expert on those and our components are still very basic. And as you said we're in the trial phase so let's see.

**Comment by samanthabaita** [comment]
@lykkechen Yes, we should put both wireframes side by side to have a clear vision of the differences between mobile and desktop.

About triggers :fire:  I think we should start with the ones you've mentioned, and then update the list when we need or use other triggers.

**Comment by samanthabaita** [comment]
@revas/everyone what do you think is missing in the enhancement? Should we start to write a document with all these cool things we discussed?

**Comment by samanthabaita** [comment]
We should also discuss about the Vue Tour and try to define some guidelines to follow, in order to have consistency in all the Revas platform. 

This tour is really useful for the people who use Revas for the first time, I would like to keep it really simple with only the necessary quantity of information. :blush:

**Comment by davidegiovanni** [comment]
> I think it would be practical also to have the desktop wireframes side by side with the mobile ones. 

As said by @lykkechen, we can export SVGs containing in one file both the desktop and the mobile view.

> I think that we could also organize the design folder in subfolders, one for each component described in the specs. In there we could have all the screens. About naming, I thought we could use a structure similar to this one: [state]-[type of component]-[desktop/mobile].svg

@samanthabaita I don't know if it would be helpful to create a folder for each components inside the design folders: components will be available as code in the library, we can use the same naming system to describe the components in the Wireframing documentation.

> I think we should consider making a list of base components and a little how to name SVG files guide.

I agree with the guide for naming. I won't create a list of components: they will be available in the components folder with their naming once they will be developed.

**Comment by samanthabaita** [comment]
> I don't know if it would be helpful to create a folder for each components inside the design folder: components will be available as code in the library, we can use the same naming system to describe the components in the Wireframing Documentation.

@davidegiovanni Now we have a small number of elements and components in a single app, but when we will have many elements in a _Revo_ and a dev would like to see a particular state, I think he should be able to easily find that SVG file. Maybe the thing that wasn't clear,  it's that I was referring to the view/components written in the specs/README.md of a revo, not every single component (for example in the case of _Alianco_ the components are two:  _list-citizens_ and the _create-realm_ )

**Comment by davidegiovanni** [comment]
Ok, maybe we are talking about two different things, but what I was saying is:

* wireframes are for developers and they have mobile and desktop screens, the triggerable elements, the type of triggers and the consequences of the trigger;
* components will be grouped in a design system library as code, with their naming and properties defined in ther code.

The question is: why should we have folders for each component and its related state? The states of the components are defined in the system library and the actions in the wireframe as long as the triggers - the wireframe and related docs are easy to navigate, in my opinio, than creating as many folders as all the states and components defined inside the wireframe, I think, becasue you can see them with one glance.

Moreover, the components defined in the README.md will be the components inside the design system library and if you use that component, it will have all the properties and behaviors defined inside it, so it would be redundant to define them again in the documentation of the wireframes.

Is my point clear? 🤔

(maybe I am talking nonsense)

**Comment by davidegiovanni** [comment]
@samanthabaita now it's clear! I was thinking about components and not about views and I was implicitly thinking what you were saying - I agree: as many folders as views we have.

But for the naimng I would use such a format:
[name of the view]-[wireframe].svg

*Example:*
> createRealm-wireframe.svg

And inside each wireframe, mobile and desktop screens one beside the other.

**Comment by samanthabaita** [comment]
Yeah, great! I'm glad that now it's all clear, maybe we should change "components" in views inside the specs documentation to avoid this misunderstanding. 

> [name of the view]-[wireframe].svg
> And inside each wireframe, mobile and desktop screens one beside the other.

That's great, I agree in this way it's more clear :blush:
