### ISSUE TITLE
Missing Contributing Guide

### ISSUE THREAD

**Issue by hashbardd** [revas/ecosystem#4]
We should add a CONTRIBUTING.md file in our repositories or maybe just one in the [ecosystem repository](https://github.com/revas/ecosystem). The [open source guide](https://opensource.guide/how-to-contribute/) has some nice starting points. @revas/everyone

**Comment by davidegiovanni** [comment]
I'd add it just to the ecosystem repository.

**Comment by hashbardd** [comment]
I'm starting to work on this issue! I'm going to take some popular projects and see if there is something interesting for our contributing guide 😸
