### ISSUE TITLE
Missing Logo Asset of the Project

### ISSUE THREAD

**Issue by davidegiovanni** [revas/ecosystem#6]
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

## Benefits

Precise and recognizable brand identity.

## Context

The project misses a logo and it's necessary to define the identity and communication of the project, and it's a missing asset for the website and platform. 

@revas/everyone

**Comment by hashbardd** [comment]
@davidegiovanni Do you have some proposals? 😄

**Comment by davidegiovanni** [comment]
Yes, I do have one - connected circles of various dimensions to express collaboration, simplicity, innovation and unity. The lettering used has a handcrafted feel yet modern and digital-ready. The logo is responsive though: it's not necessary to use the icon and the lettering together. What do you think?
![img_5140](https://user-images.githubusercontent.com/33760151/34639896-0004d65a-f2e9-11e7-8c30-785bc8dc63ce.jpg)

**Comment by samanthabaita** [comment]
@davidegiovanni I really like this proposal! Circles are a great way to express the identity of The Revas Project 😍

**Comment by hashbardd** [comment]
@davidegiovanni I love the concept, the circles express to me the different groups of people that interact with each others. The circles also remind me planets of a universe, I like the feel of openness and discoverability. The font gives me a feeling of serenity. Thank you so much! 🌟

**Comment by banh-gao** [comment]
I like the concept of overlapping circles to express collaboration.
However, having a bigger circle in the middle of the logo resembles to me a central entity to which others connect to.
I would suggest, as a way to recall more horizontal collaboration, a different disposition so that the bigger circle is not in the center.

**Comment by hashbardd** [comment]
@banh-gao I actually like the bigger circle because I don't think about it like "a central entity" but more like "that is my space connected with others". What do you think?

**Comment by davidegiovanni** [comment]
@hashbardd is right. The central circle express the unitary nature of Revas - one platform, many services.

**Comment by hashbardd** [comment]
@davidegiovanni If you are available we can wait for a pull request with the final work, so we can continue the discussion. Let us know if you want to work on this issue 😄 

@revas/everyone Other proposals or concepts are welcome :heart:

**Comment by banh-gao** [comment]
@hashbardd @davidegiovanni I think that it can be interpreted in both ways. If the central circle has a different meaning than the others then it has to be made more clear in some visual way.

**Comment by davidegiovanni** [comment]
@banh-gao we can design this logo and test it to see which way the central circle is perceived. Btw, I can design logo for the pull request 👍

**Comment by davidegiovanni** [comment]
![group](https://user-images.githubusercontent.com/33760151/34650237-f58d5d2a-f3bd-11e7-8dc2-650e17628cd9.png)
Here you are a more polished version - grey scale because I think that the color palette will be another issue.

**Comment by hashbardd** [comment]
@banh-gao Can you show us a simple sketch or a defined design suggestion of what you are thinking about? 🤔 

@davidegiovanni About @banh-gao comment, what do you think about using colors to express diversity (like [thoughtworks logo](https://cdn.evbuc.com/eventlogos/148316749/thoughtworks.png))? So we can reduce the main circle dimensions. I actually prefer having a bigger circle because the software is dedicated to the user, to her/their/his personal space within organizations.

I think that we can discuss color palette here, but if you have specific questions about that, feel free to submit a new issue. 🎨

**Comment by davidegiovanni** [comment]
@hashbardd absolutely- the idea is to use different colors for each circle.

I was planning to submit a new issue for the palette.

**Comment by hashbardd** [comment]
@davidegiovanni If you can pull two alternate versions (one with the bigger circle and one with a smaller one) it would be awesome :heart::tada:

**Comment by davidegiovanni** [comment]
![group copy](https://user-images.githubusercontent.com/33760151/34650566-6662d2f0-f3c3-11e7-80af-f722ac010713.png)
Something like that? Alignment can be fixed later. Pretty dispersive, I think.

**Comment by hashbardd** [comment]
@davidegiovanni I think that you can continue with the first design, if you want to submit a new issue for the color palette you are welcome! 😄

**Comment by davidegiovanni** [comment]
@hashbardd I'll wait for the others to answer to keep working on the first logo. Meanwhile, I'll open the other issue.

**Comment by samanthabaita** [comment]
@davidegiovanni I prefer the previous one, having more intersections between circles can express way better the principle of collaboration.

**Comment by lucyskyy** [comment]
I like the first version more too, with the bigger circle that maybe can be adjusted better once we have a color palette!

**Comment by davidegiovanni** [comment]
![logo-test](https://user-images.githubusercontent.com/33760151/34725556-968c60b0-f551-11e7-9601-e8f5426301b6.png)

What do you think?

@revas/everyone

**Comment by davidegiovanni** [comment]
![logo-test](https://user-images.githubusercontent.com/33760151/34726800-562d2de8-f555-11e7-8353-b46f317f23bb.png)

What do you think?

@revas/everyone

**Comment by samanthabaita** [comment]
@davidegiovanni I love it! ❤️

**Comment by davidegiovanni** [comment]
![gradiente](https://user-images.githubusercontent.com/33760151/34732495-c1a9c526-f565-11e7-9f16-ce6d10d497c2.png)
![navbar-brand-logo](https://user-images.githubusercontent.com/33760151/34732496-c1d94d78-f565-11e7-827e-25dc05bad6f3.png)

Logo with lettering and lettering-only with gradient (hypothetic).

@revas/designers

**Comment by samanthabaita** [comment]
@davidegiovanni I like the font and the color consistency between logo and lettering, but before taking a decision I think we can try different typefaces.

The gradient is pretty cool, but I suggest using the lettering-only gradient when there is only written "REVAS" without the logo. I find that the only-one-color matches better the logo.
For the lettering-only, what about trying to give to each letter a different color of the palette? Do you think that is a bad idea?

**Comment by hashbardd** [comment]
I think that we have something now. I like the logo and the lettering. 😄 

We can consider gradient variation after developing something in the ecosystem with some feedback from organization. We need to start working on the other components of the ecosystem!

We have so much to do, what do you think about pulling this logo and lettering? I'm sorry, I don't want to stop the creative process, but we have a product to develop :heart: @samanthabaita @davidegiovanni

**Comment by hashbardd** [comment]
Tomorrow morning we are going to pull assets for this issue and for the #7 issue 😄

**Comment by davidegiovanni** [comment]
@samanthabaita we can think about the gradient later - at the momento, for the MVP we can go for the flat version.

A lettering with different colored letters could result in something heavy for the sight. 

At the moment, I'd say we can pull these assets - the typeface is handmade and thinking about many different others could take us a lot of time.

**Comment by samanthabaita** [comment]
@davidegiovanni @hashbardd Great, we can go on with the pull and start thinking about the other components 😊

**Comment by lucyskyy** [comment]
Love the lettering and the logo 😇! Only the purple of upper-right circle seems a bit unclear, but maybe it's only my impression

**Comment by hashbardd** [comment]
@lucyskyy Yeah, the purple is a bit strange. But we are going to pull the last version and review the assets later 😄
