### ISSUE TITLE
Missing Color Palette of the Project

### ISSUE THREAD

**Issue by davidegiovanni** [revas/ecosystem#7]
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

## Benefits

Unified design system, overall consistency, strong visual identity.

## Context

The project needs a clear color palette that reflects the brand identity.

@revas/everyone

**Comment by hashbardd** [comment]
Where this color palette will be used? In the UIs or only the logo?

**Comment by davidegiovanni** [comment]
I am preparing a moodboard to share here where I am trying to visualize the colors I'd like to use.

**Comment by davidegiovanni** [comment]
@hashbardd  I guess logo but we can work also on the website palette.

**Comment by samanthabaita** [comment]
It would be nice to have a similar color palette for both the logo and the website, but we can discuss about it 😊

**Comment by davidegiovanni** [comment]
@samanthabaita Since the website is the biggest showcase of the product and the brand, that's a good point.

**Comment by hashbardd** [comment]
@davidegiovanni @samanthabaita The website is not part of the project. Here we can discuss about the color palette for the logo or software components. If you want to extend this discussion with website details you can submit a issue in the [revas.io repository](https://github.com/revas-io/revas.io). 😽

**Comment by davidegiovanni** [comment]
Ok, so I created this moodboard in InVision where we can all collaborate on the brainstorming for the project palette. I'll upload an image file here and you can access the moodboard here: https://projects.invisionapp.com/boards/MG3H6D3ZYDBSX/
<img width="809" alt="color-palette-moodboard" src="https://user-images.githubusercontent.com/33760151/34651104-d180db9c-f3cb-11e7-85df-9dc4c162df78.png">

**Comment by davidegiovanni** [comment]
Inside the moodboard there is the brand identity canvas and a moodboard for it.

**Comment by hashbardd** [comment]
The canvas needs to be translated in english. 😢

**Comment by davidegiovanni** [comment]
I know, can we leave it in Italian for the moment? I'll translate it soon.

**Comment by davidegiovanni** [comment]
@revas/everyone I have two proposals for the palette:

- palette one: #7539C1 (primary color), #D5B0F0 (secondary), #F4ACE6 (tertiary), #F4526D (primary), #FFC08E (secondary)

- palette two:  #FE736F (primary color), #FE9B93 (secondary), #FFCCC8 (tertiary), #A7E4EA (tertiary), #11C7DE (primary)

What do you think?

![palette-1](https://user-images.githubusercontent.com/33760151/34720826-805168ba-f540-11e7-8970-f2f0963df469.png)

![palette-2](https://user-images.githubusercontent.com/33760151/34720827-806e9e4e-f540-11e7-9084-eedbc8d11f8a.png)

**Comment by hashbardd** [comment]
@davidegiovanni Now I want two palettes! I can't choose 🤣

**Comment by davidegiovanni** [comment]
Personally, I prefere the second one - nice and balanced tones, inspiring calm and tranquillity (especially the pastel ones) but at the same time energy (the red side).

**Comment by hashbardd** [comment]
@davidegiovanni I prefer the second one too, but I actually love purple shading. So I leave the choice to the others contributors. :heart:

**Comment by samanthabaita** [comment]
@davidegiovanni Both palettes are nice! In the first I like the purple nuances, in the second one the first three colors. The last two of the second palette do not convince me completely.

**Comment by davidegiovanni** [comment]
![palette-def](https://user-images.githubusercontent.com/33760151/34726903-a3d88466-f555-11e7-9d7c-e8146eeee975.png)

I think this could be the final palette: #D5B0F0 (primary), #F4ACE6 (secondary), #FE736F (primary), #FE9B93 (secondary), #FFCCC8 (tertiary).

What do you think?

@revas/everyone

**Comment by samanthabaita** [comment]
@davidegiovanni Yes, for me this is the perfect color palette! It combines what we liked about the previous proposals. 😊

**Comment by lucyskyy** [comment]
The combination of the two is really great, the softness of the colors inspire a state of peacefullness.
